"""Add Document Management features

Revision ID: 9b4aab65159a
Revises: 0002
Create Date: 2026-08-12 11:30:10.676129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b4aab65159a'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_versions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('workspace_id', sa.UUID(), nullable=False),
        sa.Column('document_id', sa.UUID(), nullable=False),
        sa.Column('version_number', sa.Integer(), nullable=False),
        sa.Column('file_name', sa.String(length=500), nullable=True),
        sa.Column('file_size', sa.Integer(), nullable=True),
        sa.Column('storage_path', sa.Text(), nullable=True),
        sa.Column('checksum', sa.String(length=255), nullable=True),
        sa.Column('created_by', sa.UUID(), nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_versions_checksum'), 'document_versions', ['checksum'], unique=False)
    op.create_index(op.f('ix_document_versions_created_at'), 'document_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_document_versions_created_by'), 'document_versions', ['created_by'], unique=False)
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_versions_id'), 'document_versions', ['id'], unique=False)
    op.create_index(op.f('ix_document_versions_workspace_id'), 'document_versions', ['workspace_id'], unique=False)
    
    op.create_table('document_activities',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('workspace_id', sa.UUID(), nullable=False),
        sa.Column('document_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('activity_type', sa.String(length=100), nullable=False),
        sa.Column('details', postgresql.JSONB(), nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_activities_created_at'), 'document_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_document_activities_document_id'), 'document_activities', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_activities_id'), 'document_activities', ['id'], unique=False)
    op.create_index(op.f('ix_document_activities_user_id'), 'document_activities', ['user_id'], unique=False)
    op.create_index(op.f('ix_document_activities_workspace_id'), 'document_activities', ['workspace_id'], unique=False)
    
    op.add_column('documents', sa.Column('processing_status', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('chunk_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('checksum', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('last_processed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('documents', sa.Column('original_filename', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_documents_checksum'), 'documents', ['checksum'], unique=False)


def downgrade() -> None:
    pass
