"""add_embedding_record

Revision ID: 9f437930865f
Revises: 1d9dac339904
Create Date: 2026-08-18 18:31:16.913931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f437930865f'
down_revision: Union[str, Sequence[str], None] = '1d9dac339904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('vector_dimension', sa.Integer(), nullable=False),
    sa.Column('chunk_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embedding_records_chunk_hash'), 'embedding_records', ['chunk_hash'], unique=False)
    op.create_index(op.f('ix_embedding_records_chunk_id'), 'embedding_records', ['chunk_id'], unique=True)
    op.create_index(op.f('ix_embedding_records_document_id'), 'embedding_records', ['document_id'], unique=False)
    op.create_index(op.f('ix_embedding_records_id'), 'embedding_records', ['id'], unique=False)
    op.create_index(op.f('ix_embedding_records_workspace_id'), 'embedding_records', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embedding_records_workspace_id'), table_name='embedding_records')
    op.drop_index(op.f('ix_embedding_records_id'), table_name='embedding_records')
    op.drop_index(op.f('ix_embedding_records_document_id'), table_name='embedding_records')
    op.drop_index(op.f('ix_embedding_records_chunk_id'), table_name='embedding_records')
    op.drop_index(op.f('ix_embedding_records_chunk_hash'), table_name='embedding_records')
    op.drop_table('embedding_records')
    # ### end Alembic commands ###
